// src/components/CopyUrl.svelte
<script lang="ts">
    import Check from "@lucide/svelte/icons/check";
    import Link from "@lucide/svelte/icons/link";

    const { label, url } = $props();

    let isCopied = $state(false);

    const handleClick = () => {
        isCopied = true;

        navigator.clipboard.writeText(url);

        setTimeout(() => {
            isCopied = false;
        }, 1500);
    };
</script>

<button onclick={handleClick} class="cursor-pointer flex items-center gap-1">
    {#if isCopied}
        <Check size={20} />
        Link Copied
    {:else}
        <Link size={20} />
        {label}
    {/if}
</button>

// src/components/CopyUrl.tsx
import { useState } from "react";
import { Check, Share2 } from "lucide-react";

export default function CopyUrl({
    label,
    url
}: {
    label: string;
    url: string;
}) {
    const [isCopied, setIsCopied] = useState(false);

    const handleClick = () => {
        setIsCopied(true);
        navigator.clipboard.writeText(url);
        setTimeout(() => {
            setIsCopied(false);
        }, 1500);
    };

    return (
        <button onClick={handleClick} className="cursor-pointer flex items-center gap-1">
            {isCopied ? (
                <>
                    <Check size={20} />
                    Link Copied
                </>
            ) : (
                <>
                    <Share2 size={20} />
                    {label}
                </>
            )}
        </button>
    );
}
